# Generated by Django 5.1.3 on 2024-12-01 09:20

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('referral_code', models.CharField(max_length=6, unique=True)),
                ('auth_number', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='referral_code')),
            ],
        ),
    ]
