# Generated by Django 5.1.3 on 2024-12-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referrals',
            new_name='Referral',
        ),
    ]
