# Generated by Django 5.1.3 on 2024-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_referrals_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_number',
            field=models.IntegerField(),
        ),
    ]
