# Generated by Django 5.1.3 on 2024-12-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_auth_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(db_column='referral_code', on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='referral_code'),
        ),
    ]
